name: "Welcome New Contributors"

on:
  pull_request:
    types: opened
  issues:
    types: opened

permissions:
  pull-requests: write
  issues: write

jobs:
  welcome-message:
    name: Welcome Contributors
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Thank you for creating your first Pull Request and for being a part of the open signing revollution! 💚🚀
            <br /> Feel free to hop into our community at [Discord](https://documen.so/discord)
          issue-message: |
            Thank you for opening your first issue! <br /> One of our team members will review it and get back to you as soon as it possible.💚
