name: "Issue Assigned Status"

on:
  issues:
    types: [assigned]

permissions:
  issues: write

jobs:
  countIssues:
    if: ${{ github.event.issue.assignee }} && github.repository == 'documenso/documenso' && github.event.action == 'assigned' && github.event.sender.type == 'User'
    runs-on: ubuntu-latest
    env:
      MY_ENV_VARIABLE: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Octokit
        run: npm install @octokit/rest@18
        
      - name: Check assigned user's issue count
        id: parse-comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            
            const username = context.payload.issue.assignee.login;
            console.log(`Username extracted: ${username}`);
            
            const { data: issues } = await octokit.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignee: username,
              state: 'open'
            });
            
            const issueCount = issues.length;
            console.log(`Issue count for ${username}: ${issueCount}`);
            
            if (issueCount > 5) {
              let issueCountMessage = `@${username} has ${issueCount} open issues assigned.`;
              issueCountMessage += `\n🚨 @${username} has ${issueCount} issues assigned already. Consider whether this issue should be assigned to them or left open for another contributor 🚨`;

              await octokit.request('POST /repos/{owner}/{repo}/issues/{issue_number}/comments', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: issueCountMessage,
                headers: {
                  'Authorization': `token ${{ secrets.GITHUB_TOKEN }}`,
                }
              });
            }
