name: 'Issue Assigned Status'

on:
  issues:
    types: [assigned]

permissions:
  issues: write

jobs:
  countIssues:
    if: ${{ github.event.issue.assignee }} && github.repository == 'documenso/documenso' && github.event.action == 'assigned' && github.event.sender.type == 'User'
    runs-on: ubuntu-latest
    env:
      MY_ENV_VARIABLE: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Check assigned user's issue count
        id: parse-comment
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = context.payload.issue.assignee.login;
            console.log(`Username extracted: ${username}`);

            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignee: username,
              state: 'open'
            });

            const issueCount = issues.length;
            console.log(`Issue count for ${username}: ${issueCount}`);

            if (issueCount > 3) {
              let issueCountMessage = `@${username} has ${issueCount} open issues assigned.`;
              issueCountMessage += `\n🚨 @${username} has ${issueCount} issues assigned already. Consider whether this issue should be assigned to them or left open for another contributor 🚨`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: issueCountMessage
              });
            }
